@echo off
rem DISK-CARE DISK SCAN configuration. READ-ONLY scanner settings.
if not defined DISKCARE_TARGET set "DISKCARE_TARGET=C:\"
if not defined DISKCARE_LARGE_MB set "DISKCARE_LARGE_MB=100"
if not defined DISKCARE_OLD_DAYS set "DISKCARE_OLD_DAYS=180"
if not defined DISKCARE_OLD_MIN_MB set "DISKCARE_OLD_MIN_MB=100"
if not defined DISKCARE_RECENT_DAYS set "DISKCARE_RECENT_DAYS=30"
if not defined DISKCARE_ARTIFACT_MIN_MB set "DISKCARE_ARTIFACT_MIN_MB=100"
if not defined DISKCARE_TOP_LIMIT set "DISKCARE_TOP_LIMIT=40"
if not defined DISKCARE_LARGE_LIMIT set "DISKCARE_LARGE_LIMIT=500"
if not defined DISKCARE_OLD_LIMIT set "DISKCARE_OLD_LIMIT=500"
if not defined DISKCARE_RECENT_LIMIT set "DISKCARE_RECENT_LIMIT=500"
if not defined DISKCARE_ARTIFACT_LIMIT set "DISKCARE_ARTIFACT_LIMIT=500"
if not defined DISKCARE_DIAG_LEVEL set "DISKCARE_DIAG_LEVEL=FULL"
if not defined DISKCARE_REPORT_DIR set "DISKCARE_REPORT_DIR=%~dp0..\Output\Scan"
if not exist "%DISKCARE_REPORT_DIR%" mkdir "%DISKCARE_REPORT_DIR%" >nul 2>&1
exit /b 0
